[package]
name = "deno-hash"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
repository = "https://github.com/denoland/deno"

[lib]
crate-type = ["cdylib"]

[dependencies]
digest = "0.9.0"
md2 = "0.9.0"
md4 = "0.9.0"
md-5 = "0.9.1"
ripemd160 = "0.9.1"
ripemd320 = "0.9.0"
sha-1 = "0.9.1"
sha2 = "0.9.1"
sha3 = "0.9.1"
wasm-bindgen = "0.2.74"
blake3 = "0.3.8"
tiger = "0.1.0"

[profile.release]
lto = true
opt-level = 3
