# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_timers"
version = "0.33.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Timers API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.117.0", path = "../../core" }
tokio = { version = "1.10.1", features = ["full"] }

[dev-dependencies]
deno_bench_util = { version = "0.29.0", path = "../../bench_util" }
deno_url = { version = "0.35.0", path = "../url" }
deno_web = { version = "0.66.0", path = "../web" }
deno_webidl = { version = "0.35.0", path = "../webidl" }

[[bench]]
name = "timers_ops"
harness = false
