# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
[package]
name = "serde_v8"
version = "0.28.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Rust to V8 serialization and deserialization"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_bytes = "0.11"
v8 = "0.39.0"

[dev-dependencies]
bencher = "0.1"
serde_json = "1.0.64"

[[example]]
name = "basic"

[[bench]]
name = "de"
harness = false

[[bench]]
name = "ser"
harness = false
