# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_net"
version = "0.27.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Networking for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.117.0", path = "../../core" }
deno_tls = { version = "0.22.0", path = "../tls" }
log = "0.4.14"
serde = { version = "1.0.129", features = ["derive"] }
socket2 = "0.4.2"
tokio = { version = "1.10.1", features = ["full"] }
trust-dns-proto = "0.20.3"
trust-dns-resolver = { version = "0.20.3", features = ["tokio-runtime", "serde-config"] }
