# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.49.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Web Cryptography API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
aes = "0.7.5"
aes-gcm = "0.9.4"
aes-kw = { version = "0.1", features = ["alloc"] }
base64 = "0.13.0"
block-modes = "0.8.1"
ctr = "0.8.0"
deno_core = { version = "0.117.0", path = "../../core" }
deno_web = { version = "0.66.0", path = "../web" }
elliptic-curve = { version = "0.10.6", features = ["std", "pem"] }
num-traits = "0.2.14"
once_cell = "=1.9.0"
p256 = { version = "0.9.0", features = ["ecdh"] }
p384 = "0.8.0"
rand = "0.8.4"
ring = { version = "0.16.20", features = ["std"] }
rsa = { version = "0.5.0", default-features = false, features = ["std"] }
serde = { version = "1.0.129", features = ["derive"] }
serde_bytes = "0.11"
sha-1 = "0.9.7"
sha2 = "0.9.5"
spki = "0.4.1"
tokio = { version = "1.10.1", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
