# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_fetch"
version = "0.58.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Fetch API implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
bytes = "1.1.0"
data-url = "0.1.0"
deno_core = { version = "0.117.0", path = "../../core" }
deno_tls = { version = "0.22.0", path = "../tls" }
dyn-clone = "1"
http = "0.2.4"
reqwest = { version = "0.11.7", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
serde = { version = "1.0.129", features = ["derive"] }
tokio = { version = "1.10.1", features = ["full"] }
tokio-stream = "0.1.7"
tokio-util = "0.6.7"
