# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_web"
version = "0.66.0"
authors = ["the Deno authors"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "Collection of Web APIs"

[lib]
path = "lib.rs"

[dependencies]
async-trait = "0.1.51"
base64 = "0.13.0"
deno_core = { version = "0.117.0", path = "../../core" }
encoding_rs = "0.8.29"
flate2 = "1"
serde = "1.0.129"
tokio = { version = "1.10.1", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
