# Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.

[package]
name = "test_util"
version = "0.1.0"
authors = ["the Deno authors"]
edition = "2021"
publish = false

[[bin]]
name = "test_server"
path = "src/test_server.rs"

[dependencies]
anyhow = "1.0.43"
async-stream = "0.3.2"
atty = "0.2.14"
base64 = "0.13.0"
futures = "0.3.16"
hyper = { version = "0.14.12", features = ["server", "http1", "http2", "runtime"] }
lazy_static = "1.4.0"
os_pipe = "0.9.2"
regex = "1.5.4"
rustls-pemfile = "0.2.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.65"
tempfile = "3.2.0"
tokio = { version = "1.10.1", features = ["full"] }
tokio-rustls = "0.23"
tokio-tungstenite = "0.16"

[target.'cfg(unix)'.dependencies]
pty = "0.2.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["consoleapi", "handleapi", "namedpipeapi", "winbase", "winerror"] }
